// Results-showcase data. Each entry describes one generated artefact that
// the landing page should display in the ResultsShowcase section.
//
// HOW TO SWAP IN A REAL OUTPUT
// ────────────────────────────
//  1. Generate the artefact through the Gathos API using the `prompt` field.
//  2. Drop the file at the `src` path under /public (e.g. /public/showcase/
//     images/img-01.webp).
//  3. Set `ready: true` on the entry. The component will render the real
//     file and the gradient placeholder will disappear.
//
// Until `ready: true` the component renders a styled gradient card with the
// prompt text — so the layout, animations, and spacing are testable on
// dev.gathos.com without any binary assets present.
//
// Gradient swatches map to the cream / matcha / slushie / ube / lemon /
// dragonfruit palette in tailwind.config.js to stay on-brand even as
// placeholders.

// Curated to 6 — the strongest "image with rendered text" pieces
// (Tokyo, YouTube thumbnail, editorial spread, Bauhaus poster) plus a
// cinematic and a stylised illustration to show range. Removed: coffee
// mug, app onboarding, infographic, sneaker banner — solid but they
// pushed the section past one viewport.
export const IMAGE_RESULTS = [
  {
    id: 'img-01',
    prompt: 'Polished square text-to-image result from the Gathos prompt set, built for product, character, and campaign visuals with crisp composition.',
    aspect: 'square',
    swatch: 'cream',
    feature: 'Square format',
    ready: true,
    src: '/showcase/images/t2i-drive-webp/g8hos_perfect_100_square.webp',
  },
  {
    id: 'img-02',
    prompt: 'Wide text-to-image campaign visual from the Gathos prompt set, ready for landing pages, ads, thumbnails, and social creative.',
    aspect: 'horizontal',
    swatch: 'matcha',
    feature: 'Horizontal campaign',
    ready: true,
    src: '/showcase/images/t2i-drive-webp/g8hos_perfect_099_horizontal.webp',
  },
  {
    id: 'img-03',
    prompt: 'Polished square text-to-image result from the Gathos prompt set, built for product, character, and campaign visuals with crisp composition.',
    aspect: 'square',
    swatch: 'slushie',
    feature: 'Square format',
    ready: true,
    src: '/showcase/images/t2i-drive-webp/g8hos_perfect_097_square.webp',
  },
  {
    id: 'img-04',
    prompt: 'Wide text-to-image campaign visual from the Gathos prompt set, ready for landing pages, ads, thumbnails, and social creative.',
    aspect: 'horizontal',
    swatch: 'ube',
    feature: 'Horizontal campaign',
    ready: true,
    src: '/showcase/images/t2i-drive-webp/g8hos_perfect_096_horizontal.webp',
  },
  {
    id: 'img-05',
    prompt: 'Polished square text-to-image result from the Gathos prompt set, built for product, character, and campaign visuals with crisp composition.',
    aspect: 'square',
    swatch: 'lemon',
    feature: 'Square format',
    ready: true,
    src: '/showcase/images/t2i-drive-webp/g8hos_perfect_091_square.webp',
  },
  {
    id: 'img-06',
    prompt: 'Vertical text-to-image result from the Gathos prompt set, shaped for posters, mobile creative, storyboards, and production concepts.',
    aspect: 'vertical',
    swatch: 'dragonfruit',
    feature: 'Vertical creative',
    ready: true,
    src: '/showcase/images/t2i-drive-webp/g8hos_perfect_089_vertical.webp',
  },
  {
    id: 'img-07',
    prompt: 'Wide text-to-image campaign visual from the Gathos prompt set, ready for landing pages, ads, thumbnails, and social creative.',
    aspect: 'horizontal',
    swatch: 'cream',
    feature: 'Horizontal campaign',
    ready: true,
    src: '/showcase/images/t2i-drive-webp/g8hos_perfect_087_horizontal.webp',
  },
  {
    id: 'img-08',
    prompt: 'Vertical text-to-image result from the Gathos prompt set, shaped for posters, mobile creative, storyboards, and production concepts.',
    aspect: 'vertical',
    swatch: 'matcha',
    feature: 'Vertical creative',
    ready: true,
    src: '/showcase/images/t2i-drive-webp/g8hos_perfect_086_vertical.webp',
  },
  {
    id: 'img-09',
    prompt: 'Polished square text-to-image result from the Gathos prompt set, built for product, character, and campaign visuals with crisp composition.',
    aspect: 'square',
    swatch: 'slushie',
    feature: 'Square format',
    ready: true,
    src: '/showcase/images/t2i-drive-webp/g8hos_perfect_085_square.webp',
  },
  {
    id: 'img-10',
    prompt: 'Wide text-to-image campaign visual from the Gathos prompt set, ready for landing pages, ads, thumbnails, and social creative.',
    aspect: 'horizontal',
    swatch: 'ube',
    feature: 'Horizontal campaign',
    ready: true,
    src: '/showcase/images/t2i-drive-webp/g8hos_perfect_084_horizontal.webp',
  },
  {
    id: 'img-11',
    prompt: 'Vertical text-to-image result from the Gathos prompt set, shaped for posters, mobile creative, storyboards, and production concepts.',
    aspect: 'vertical',
    swatch: 'lemon',
    feature: 'Vertical creative',
    ready: true,
    src: '/showcase/images/t2i-drive-webp/g8hos_perfect_083_vertical.webp',
  },
  {
    id: 'img-12',
    prompt: 'Polished square text-to-image result from the Gathos prompt set, built for product, character, and campaign visuals with crisp composition.',
    aspect: 'square',
    swatch: 'dragonfruit',
    feature: 'Square format',
    ready: true,
    src: '/showcase/images/t2i-drive-webp/g8hos_perfect_082_square.webp',
  },
  {
    id: 'img-13',
    prompt: 'Wide text-to-image campaign visual from the Gathos prompt set, ready for landing pages, ads, thumbnails, and social creative.',
    aspect: 'horizontal',
    swatch: 'cream',
    feature: 'Horizontal campaign',
    ready: true,
    src: '/showcase/images/t2i-drive-webp/g8hos_perfect_081_horizontal.webp',
  },
  {
    id: 'img-14',
    prompt: 'Polished square text-to-image result from the Gathos prompt set, built for product, character, and campaign visuals with crisp composition.',
    aspect: 'square',
    swatch: 'matcha',
    feature: 'Square format',
    ready: true,
    src: '/showcase/images/t2i-drive-webp/g8hos_perfect_079_square.webp',
  },
  {
    id: 'img-15',
    prompt: 'Wide text-to-image campaign visual from the Gathos prompt set, ready for landing pages, ads, thumbnails, and social creative.',
    aspect: 'horizontal',
    swatch: 'slushie',
    feature: 'Horizontal campaign',
    ready: true,
    src: '/showcase/images/t2i-drive-webp/g8hos_perfect_078_horizontal.webp',
  },
  {
    id: 'img-16',
    prompt: 'Vertical text-to-image result from the Gathos prompt set, shaped for posters, mobile creative, storyboards, and production concepts.',
    aspect: 'vertical',
    swatch: 'ube',
    feature: 'Vertical creative',
    ready: true,
    src: '/showcase/images/t2i-drive-webp/g8hos_perfect_077_vertical.webp',
  },
  {
    id: 'img-17',
    prompt: 'Polished square text-to-image result from the Gathos prompt set, built for product, character, and campaign visuals with crisp composition.',
    aspect: 'square',
    swatch: 'lemon',
    feature: 'Square format',
    ready: true,
    src: '/showcase/images/t2i-drive-webp/g8hos_perfect_076_square.webp',
  },
  {
    id: 'img-18',
    prompt: 'Wide text-to-image campaign visual from the Gathos prompt set, ready for landing pages, ads, thumbnails, and social creative.',
    aspect: 'horizontal',
    swatch: 'dragonfruit',
    feature: 'Horizontal campaign',
    ready: true,
    src: '/showcase/images/t2i-drive-webp/g8hos_perfect_075_horizontal.webp',
  },
  {
    id: 'img-19',
    prompt: 'Vertical text-to-image result from the Gathos prompt set, shaped for posters, mobile creative, storyboards, and production concepts.',
    aspect: 'vertical',
    swatch: 'cream',
    feature: 'Vertical creative',
    ready: true,
    src: '/showcase/images/t2i-drive-webp/g8hos_perfect_074_vertical.webp',
  },
  {
    id: 'img-20',
    prompt: 'Polished square text-to-image result from the Gathos prompt set, built for product, character, and campaign visuals with crisp composition.',
    aspect: 'square',
    swatch: 'matcha',
    feature: 'Square format',
    ready: true,
    src: '/showcase/images/t2i-drive-webp/g8hos_perfect_073_square.webp',
  },
  {
    id: 'img-21',
    prompt: 'Wide text-to-image campaign visual from the Gathos prompt set, ready for landing pages, ads, thumbnails, and social creative.',
    aspect: 'horizontal',
    swatch: 'slushie',
    feature: 'Horizontal campaign',
    ready: true,
    src: '/showcase/images/t2i-drive-webp/g8hos_perfect_072_horizontal.webp',
  },
  {
    id: 'img-22',
    prompt: 'Vertical text-to-image result from the Gathos prompt set, shaped for posters, mobile creative, storyboards, and production concepts.',
    aspect: 'vertical',
    swatch: 'ube',
    feature: 'Vertical creative',
    ready: true,
    src: '/showcase/images/t2i-drive-webp/g8hos_perfect_071_vertical.webp',
  },
  {
    id: 'img-23',
    prompt: 'Wide text-to-image campaign visual from the Gathos prompt set, ready for landing pages, ads, thumbnails, and social creative.',
    aspect: 'horizontal',
    swatch: 'lemon',
    feature: 'Horizontal campaign',
    ready: true,
    src: '/showcase/images/t2i-drive-webp/g8hos_perfect_069_horizontal.webp',
  },
  {
    id: 'img-24',
    prompt: 'Vertical text-to-image result from the Gathos prompt set, shaped for posters, mobile creative, storyboards, and production concepts.',
    aspect: 'vertical',
    swatch: 'dragonfruit',
    feature: 'Vertical creative',
    ready: true,
    src: '/showcase/images/t2i-drive-webp/g8hos_perfect_068_vertical.webp',
  },
  {
    id: 'img-25',
    prompt: 'Polished square text-to-image result from the Gathos prompt set, built for product, character, and campaign visuals with crisp composition.',
    aspect: 'square',
    swatch: 'cream',
    feature: 'Square format',
    ready: true,
    src: '/showcase/images/t2i-drive-webp/g8hos_perfect_067_square.webp',
  },
  {
    id: 'img-26',
    prompt: 'Vertical text-to-image result from the Gathos prompt set, shaped for posters, mobile creative, storyboards, and production concepts.',
    aspect: 'vertical',
    swatch: 'matcha',
    feature: 'Vertical creative',
    ready: true,
    src: '/showcase/images/t2i-drive-webp/g8hos_perfect_065_vertical.webp',
  },
  {
    id: 'img-27',
    prompt: 'Polished square text-to-image result from the Gathos prompt set, built for product, character, and campaign visuals with crisp composition.',
    aspect: 'square',
    swatch: 'slushie',
    feature: 'Square format',
    ready: true,
    src: '/showcase/images/t2i-drive-webp/g8hos_perfect_064_square.webp',
  },
  {
    id: 'img-28',
    prompt: 'Wide text-to-image campaign visual from the Gathos prompt set, ready for landing pages, ads, thumbnails, and social creative.',
    aspect: 'horizontal',
    swatch: 'ube',
    feature: 'Horizontal campaign',
    ready: true,
    src: '/showcase/images/t2i-drive-webp/g8hos_perfect_063_horizontal.webp',
  },
  {
    id: 'img-29',
    prompt: 'Polished square text-to-image result from the Gathos prompt set, built for product, character, and campaign visuals with crisp composition.',
    aspect: 'square',
    swatch: 'lemon',
    feature: 'Square format',
    ready: true,
    src: '/showcase/images/t2i-drive-webp/g8hos_perfect_061_square.webp',
  },
  {
    id: 'img-30',
    prompt: 'Wide text-to-image campaign visual from the Gathos prompt set, ready for landing pages, ads, thumbnails, and social creative.',
    aspect: 'horizontal',
    swatch: 'dragonfruit',
    feature: 'Horizontal campaign',
    ready: true,
    src: '/showcase/images/t2i-drive-webp/g8hos_perfect_060_horizontal.webp',
  },
  {
    id: 'img-31',
    prompt: 'Vertical text-to-image result from the Gathos prompt set, shaped for posters, mobile creative, storyboards, and production concepts.',
    aspect: 'vertical',
    swatch: 'cream',
    feature: 'Vertical creative',
    ready: true,
    src: '/showcase/images/t2i-drive-webp/g8hos_perfect_059_vertical.webp',
  },
  {
    id: 'img-32',
    prompt: 'Vertical text-to-image result from the Gathos prompt set, shaped for posters, mobile creative, storyboards, and production concepts.',
    aspect: 'vertical',
    swatch: 'matcha',
    feature: 'Vertical creative',
    ready: true,
    src: '/showcase/images/t2i-drive-webp/g8hos_perfect_056_vertical.webp',
  },
  {
    id: 'img-33',
    prompt: 'Polished square text-to-image result from the Gathos prompt set, built for product, character, and campaign visuals with crisp composition.',
    aspect: 'square',
    swatch: 'slushie',
    feature: 'Square format',
    ready: true,
    src: '/showcase/images/t2i-drive-webp/g8hos_perfect_055_square.webp',
  },
  {
    id: 'img-34',
    prompt: 'Vertical text-to-image result from the Gathos prompt set, shaped for posters, mobile creative, storyboards, and production concepts.',
    aspect: 'vertical',
    swatch: 'ube',
    feature: 'Vertical creative',
    ready: true,
    src: '/showcase/images/t2i-drive-webp/g8hos_perfect_053_vertical.webp',
  },
  {
    id: 'img-35',
    prompt: 'Polished square text-to-image result from the Gathos prompt set, built for product, character, and campaign visuals with crisp composition.',
    aspect: 'square',
    swatch: 'lemon',
    feature: 'Square format',
    ready: true,
    src: '/showcase/images/t2i-drive-webp/g8hos_perfect_052_square.webp',
  },
  {
    id: 'img-36',
    prompt: 'Wide text-to-image campaign visual from the Gathos prompt set, ready for landing pages, ads, thumbnails, and social creative.',
    aspect: 'horizontal',
    swatch: 'dragonfruit',
    feature: 'Horizontal campaign',
    ready: true,
    src: '/showcase/images/t2i-drive-webp/g8hos_perfect_051_horizontal.webp',
  },
  {
    id: 'img-37',
    prompt: 'Vertical text-to-image result from the Gathos prompt set, shaped for posters, mobile creative, storyboards, and production concepts.',
    aspect: 'vertical',
    swatch: 'cream',
    feature: 'Vertical creative',
    ready: true,
    src: '/showcase/images/t2i-drive-webp/g8hos_perfect_050_vertical.webp',
  },
  {
    id: 'img-38',
    prompt: 'Polished square text-to-image result from the Gathos prompt set, built for product, character, and campaign visuals with crisp composition.',
    aspect: 'square',
    swatch: 'matcha',
    feature: 'Square format',
    ready: true,
    src: '/showcase/images/t2i-drive-webp/g8hos_perfect_049_square.webp',
  },
  {
    id: 'img-39',
    prompt: 'Wide text-to-image campaign visual from the Gathos prompt set, ready for landing pages, ads, thumbnails, and social creative.',
    aspect: 'horizontal',
    swatch: 'slushie',
    feature: 'Horizontal campaign',
    ready: true,
    src: '/showcase/images/t2i-drive-webp/g8hos_perfect_048_horizontal.webp',
  },
  {
    id: 'img-40',
    prompt: 'Vertical text-to-image result from the Gathos prompt set, shaped for posters, mobile creative, storyboards, and production concepts.',
    aspect: 'vertical',
    swatch: 'ube',
    feature: 'Vertical creative',
    ready: true,
    src: '/showcase/images/t2i-drive-webp/g8hos_perfect_047_vertical.webp',
  },
  {
    id: 'img-41',
    prompt: 'Wide text-to-image campaign visual from the Gathos prompt set, ready for landing pages, ads, thumbnails, and social creative.',
    aspect: 'horizontal',
    swatch: 'lemon',
    feature: 'Horizontal campaign',
    ready: true,
    src: '/showcase/images/t2i-drive-webp/g8hos_perfect_045_horizontal.webp',
  },
  {
    id: 'img-42',
    prompt: 'Vertical text-to-image result from the Gathos prompt set, shaped for posters, mobile creative, storyboards, and production concepts.',
    aspect: 'vertical',
    swatch: 'dragonfruit',
    feature: 'Vertical creative',
    ready: true,
    src: '/showcase/images/t2i-drive-webp/g8hos_perfect_044_vertical.webp',
  },
  {
    id: 'img-43',
    prompt: 'Polished square text-to-image result from the Gathos prompt set, built for product, character, and campaign visuals with crisp composition.',
    aspect: 'square',
    swatch: 'cream',
    feature: 'Square format',
    ready: true,
    src: '/showcase/images/t2i-drive-webp/g8hos_perfect_043_square.webp',
  },
  {
    id: 'img-44',
    prompt: 'Wide text-to-image campaign visual from the Gathos prompt set, ready for landing pages, ads, thumbnails, and social creative.',
    aspect: 'horizontal',
    swatch: 'matcha',
    feature: 'Horizontal campaign',
    ready: true,
    src: '/showcase/images/t2i-drive-webp/g8hos_perfect_042_horizontal.webp',
  },
  {
    id: 'img-45',
    prompt: 'Vertical text-to-image result from the Gathos prompt set, shaped for posters, mobile creative, storyboards, and production concepts.',
    aspect: 'vertical',
    swatch: 'slushie',
    feature: 'Vertical creative',
    ready: true,
    src: '/showcase/images/t2i-drive-webp/g8hos_perfect_041_vertical.webp',
  },
  {
    id: 'img-46',
    prompt: 'Polished square text-to-image result from the Gathos prompt set, built for product, character, and campaign visuals with crisp composition.',
    aspect: 'square',
    swatch: 'ube',
    feature: 'Square format',
    ready: true,
    src: '/showcase/images/t2i-drive-webp/g8hos_perfect_040_square.webp',
  },
  {
    id: 'img-47',
    prompt: 'Wide text-to-image campaign visual from the Gathos prompt set, ready for landing pages, ads, thumbnails, and social creative.',
    aspect: 'horizontal',
    swatch: 'lemon',
    feature: 'Horizontal campaign',
    ready: true,
    src: '/showcase/images/t2i-drive-webp/g8hos_perfect_036_horizontal.webp',
  },
  {
    id: 'img-48',
    prompt: 'Vertical text-to-image result from the Gathos prompt set, shaped for posters, mobile creative, storyboards, and production concepts.',
    aspect: 'vertical',
    swatch: 'dragonfruit',
    feature: 'Vertical creative',
    ready: true,
    src: '/showcase/images/t2i-drive-webp/g8hos_perfect_035_vertical.webp',
  },
  {
    id: 'img-49',
    prompt: 'Polished square text-to-image result from the Gathos prompt set, built for product, character, and campaign visuals with crisp composition.',
    aspect: 'square',
    swatch: 'cream',
    feature: 'Square format',
    ready: true,
    src: '/showcase/images/t2i-drive-webp/g8hos_perfect_034_square.webp',
  },
  {
    id: 'img-50',
    prompt: 'Vertical text-to-image result from the Gathos prompt set, shaped for posters, mobile creative, storyboards, and production concepts.',
    aspect: 'vertical',
    swatch: 'matcha',
    feature: 'Vertical creative',
    ready: true,
    src: '/showcase/images/t2i-drive-webp/g8hos_perfect_032_vertical.webp',
  },
  {
    id: 'img-51',
    prompt: 'Polished square text-to-image result from the Gathos prompt set, built for product, character, and campaign visuals with crisp composition.',
    aspect: 'square',
    swatch: 'slushie',
    feature: 'Square format',
    ready: true,
    src: '/showcase/images/t2i-drive-webp/g8hos_perfect_031_square.webp',
  },
  {
    id: 'img-52',
    prompt: 'Vertical text-to-image result from the Gathos prompt set, shaped for posters, mobile creative, storyboards, and production concepts.',
    aspect: 'vertical',
    swatch: 'ube',
    feature: 'Vertical creative',
    ready: true,
    src: '/showcase/images/t2i-drive-webp/g8hos_perfect_029_vertical.webp',
  },
  {
    id: 'img-53',
    prompt: 'Polished square text-to-image result from the Gathos prompt set, built for product, character, and campaign visuals with crisp composition.',
    aspect: 'square',
    swatch: 'lemon',
    feature: 'Square format',
    ready: true,
    src: '/showcase/images/t2i-drive-webp/g8hos_perfect_028_square.webp',
  },
  {
    id: 'img-54',
    prompt: 'Wide text-to-image campaign visual from the Gathos prompt set, ready for landing pages, ads, thumbnails, and social creative.',
    aspect: 'horizontal',
    swatch: 'dragonfruit',
    feature: 'Horizontal campaign',
    ready: true,
    src: '/showcase/images/t2i-drive-webp/g8hos_perfect_027_horizontal.webp',
  },
  {
    id: 'img-55',
    prompt: 'Vertical text-to-image result from the Gathos prompt set, shaped for posters, mobile creative, storyboards, and production concepts.',
    aspect: 'vertical',
    swatch: 'cream',
    feature: 'Vertical creative',
    ready: true,
    src: '/showcase/images/t2i-drive-webp/g8hos_perfect_023_vertical.webp',
  },
  {
    id: 'img-56',
    prompt: 'Polished square text-to-image result from the Gathos prompt set, built for product, character, and campaign visuals with crisp composition.',
    aspect: 'square',
    swatch: 'matcha',
    feature: 'Square format',
    ready: true,
    src: '/showcase/images/t2i-drive-webp/g8hos_perfect_022_square.webp',
  },
  {
    id: 'img-57',
    prompt: 'Wide text-to-image campaign visual from the Gathos prompt set, ready for landing pages, ads, thumbnails, and social creative.',
    aspect: 'horizontal',
    swatch: 'slushie',
    feature: 'Horizontal campaign',
    ready: true,
    src: '/showcase/images/t2i-drive-webp/g8hos_perfect_021_horizontal.webp',
  },
  {
    id: 'img-58',
    prompt: 'Wide text-to-image campaign visual from the Gathos prompt set, ready for landing pages, ads, thumbnails, and social creative.',
    aspect: 'horizontal',
    swatch: 'ube',
    feature: 'Horizontal campaign',
    ready: true,
    src: '/showcase/images/t2i-drive-webp/g8hos_perfect_018_horizontal.webp',
  },
  {
    id: 'img-59',
    prompt: 'Wide text-to-image campaign visual from the Gathos prompt set, ready for landing pages, ads, thumbnails, and social creative.',
    aspect: 'horizontal',
    swatch: 'lemon',
    feature: 'Horizontal campaign',
    ready: true,
    src: '/showcase/images/t2i-drive-webp/g8hos_perfect_015_horizontal.webp',
  },
  {
    id: 'img-60',
    prompt: 'Wide text-to-image campaign visual from the Gathos prompt set, ready for landing pages, ads, thumbnails, and social creative.',
    aspect: 'horizontal',
    swatch: 'dragonfruit',
    feature: 'Horizontal campaign',
    ready: true,
    src: '/showcase/images/t2i-drive-webp/g8hos_perfect_012_horizontal.webp',
  },
  {
    id: 'img-61',
    prompt: 'Vertical text-to-image result from the Gathos prompt set, shaped for posters, mobile creative, storyboards, and production concepts.',
    aspect: 'vertical',
    swatch: 'cream',
    feature: 'Vertical creative',
    ready: true,
    src: '/showcase/images/t2i-drive-webp/g8hos_perfect_011_vertical.webp',
  },
  {
    id: 'img-62',
    prompt: 'Polished square text-to-image result from the Gathos prompt set, built for product, character, and campaign visuals with crisp composition.',
    aspect: 'square',
    swatch: 'matcha',
    feature: 'Square format',
    ready: true,
    src: '/showcase/images/t2i-drive-webp/g8hos_perfect_010_square.webp',
  },
  {
    id: 'img-63',
    prompt: 'Wide text-to-image campaign visual from the Gathos prompt set, ready for landing pages, ads, thumbnails, and social creative.',
    aspect: 'horizontal',
    swatch: 'slushie',
    feature: 'Horizontal campaign',
    ready: true,
    src: '/showcase/images/t2i-drive-webp/g8hos_perfect_009_horizontal.webp',
  },
  {
    id: 'img-64',
    prompt: 'Polished square text-to-image result from the Gathos prompt set, built for product, character, and campaign visuals with crisp composition.',
    aspect: 'square',
    swatch: 'ube',
    feature: 'Square format',
    ready: true,
    src: '/showcase/images/t2i-drive-webp/g8hos_perfect_007_square.webp',
  },
  {
    id: 'img-65',
    prompt: 'Vertical text-to-image result from the Gathos prompt set, shaped for posters, mobile creative, storyboards, and production concepts.',
    aspect: 'vertical',
    swatch: 'lemon',
    feature: 'Vertical creative',
    ready: true,
    src: '/showcase/images/t2i-drive-webp/g8hos_perfect_005_vertical.webp',
  },
  {
    id: 'img-66',
    prompt: 'Wide text-to-image campaign visual from the Gathos prompt set, ready for landing pages, ads, thumbnails, and social creative.',
    aspect: 'horizontal',
    swatch: 'dragonfruit',
    feature: 'Horizontal campaign',
    ready: true,
    src: '/showcase/images/t2i-drive-webp/g8hos_perfect_003_horizontal.webp',
  }
]

// One of the image entries is "featured" — rendered larger as the hero
// tile of the masonry grid. Pick the one that most clearly demonstrates
// long-text-in-image (Gathos' sharpest differentiator).
export const FEATURED_IMAGE_ID = 'img-01'

export const VOICE_RESULTS = [
  {
    id: 'voice-01',
    language: 'English (US)',
    flag: 'US',
    voice: 'Josh · preset',
    script: 'Every voice that returns sounds like it meant to say that. Calibrated pacing, intent on every syllable, and the right inflection to land the close.',
    kind: 'preset',
    ready: true,
    src: '/showcase/audio/english-tts-preset-josh.mp3',
  },
  {
    id: 'voice-02',
    language: 'English (US)',
    flag: 'US',
    voice: 'Pixxy · preset',
    script: 'Three hundred thousand voices, six hundred languages, one single API. Your agent speaks — and it sounds exactly the way you want it to.',
    kind: 'preset',
    ready: true,
    src: '/showcase/audio/english-tts-preset-pixxy.mp3',
  },
  {
    id: 'voice-03',
    language: 'Hindi',
    flag: 'IN',
    voice: 'Sia · zero-shot clone',
    script: 'आपकी अपनी आवाज़, आपकी हर भाषा में। बस एक छोटा सैंपल अपलोड कीजिए — और छह सौ से ज़्यादा भाषाओं में आपकी ही आवाज़ बोलने लगती है, बिल्कुल स्वाभाविक।',
    kind: 'clone',
    ready: true,
    src: '/showcase/audio/hindi-voice-clone-sia.mp3',
  },
  {
    id: 'voice-04',
    language: 'Russian',
    flag: 'RU',
    voice: 'Egor · zero-shot clone',
    script: 'Один короткий образец — и Gathos мгновенно клонирует ваш голос на любом из шестисот языков. Звучит естественно, как живая речь.',
    kind: 'clone',
    ready: true,
    src: '/showcase/audio/russian-voice-clone-egor.mp3',
  },
  {
    id: 'voice-05',
    language: 'Spanish (Colombia)',
    flag: 'CO',
    voice: 'Serena · zero-shot clone',
    script: 'Una sola muestra y Gathos clona tu voz al instante. Habla en seiscientos idiomas — y suena exactamente como tú quieres que suene.',
    kind: 'clone',
    ready: true,
    src: '/showcase/audio/spanish-voice-clone-serena.mp3',
  },
  {
    id: 'voice-06',
    language: 'Italian',
    flag: 'IT',
    voice: 'Cornelia · zero-shot clone',
    script: 'Un solo campione e Gathos clona la tua voce all’istante. Parla in oltre seicento lingue, e suona proprio come la pensi.',
    kind: 'clone',
    ready: true,
    src: '/showcase/audio/italian-voice-clone-cornelia.mp3',
  },
]

// Each video showcases Gathos Creator's actual differentiator vs Veo /
// Seedance: text-to-video WITH AI-generated audio (lip-synced speech) in
// a single API call. The prompt's quoted dialogue is what the character
// speaks; the audio track is generated alongside the visual frames.
export const VIDEO_RESULTS = [
  {
    id: 'video-01',
    prompt: 'Nature b-roll: forest stream over smooth pebbles, dappled morning light, AI-generated water trickle + birdsong.',
    duration: '10s · 1280×736',
    swatch: 'slushie',
    ready: true,
    src: '/showcase/video/forest-stream-natural-audio-broll.mp4',
  },
  {
    id: 'video-02',
    prompt: 'Product demo: "This entire ad — script, voice, and video — was generated in under three minutes."',
    duration: '10s · 1280×736',
    swatch: 'slushie',
    ready: true,
    src: '/showcase/video/product-demo-creator-video.mp4',
  },
  {
    id: 'video-03',
    prompt: 'Hindi narrator: "मेरी आवाज़, मेरी भाषा — और सब कुछ एक ही API से।"',
    duration: '10s · 1280×736',
    swatch: 'ube',
    ready: true,
    src: '/showcase/video/hindi-speaker-creator-video.mp4',
  },
  {
    id: 'video-04',
    prompt: 'Pixar-style animated short: tiny cartoon robot rolling through a sunlit wildflower meadow, AI-generated whimsical score + soft mechanical whirring.',
    duration: '10s · 1280×736',
    swatch: 'matcha',
    ready: true,
    src: '/showcase/video/pixar-style-animated-short.mp4',
  },
  {
    id: 'video-05',
    prompt: 'Macro lifestyle: cracking an egg into a sizzling cast-iron pan, AI-generated egg-crack + continuous sizzle foley.',
    duration: '10s · 1280×736',
    swatch: 'lemon',
    ready: true,
    src: '/showcase/video/egg-sizzle-foley-macro-shot.mp4',
  },
  {
    id: 'video-06',
    prompt: 'Neo-noir cinematic: detective on a rain-soaked neon street at midnight. "It always ends the same way — with someone running, and someone else watching."',
    duration: '10s · 1280×736',
    swatch: 'dragonfruit',
    ready: true,
    src: '/showcase/video/neo-noir-detective-cinematic.mp4',
  },
]
